# This is a basic workflow to help you get started with Actions

name: GenerateYaml

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
      - release**
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2

      - name: Run render-cd.sh
        run: |
          set -xe
          chmod +x .github/workflows/render-cd.sh
          .github/workflows/render-cd.sh

          echo "current branch: ${{ steps.branch-name.outputs.current_branch }}"

      - name: Abstract the repository name from env.
        uses: bhowell2/github-substring-action@v1.0.0
        id: repository_name
        with:
          value: ${{github.repository}}-manifests
          index_of_str: ${{ github.repository_owner }}/

      - name: Pushes to the repository for argocd
        uses: cpina/github-action-push-to-another-repository@v1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'output'
          destination-github-username: ${{ github.repository_owner }}
          destination-repository-name: ${{ steps.repository_name.outputs.substring }}
          user-email: 'taco_support@sk.com'
          commit-message: See ORIGIN_COMMIT
          target-branch: ${{ steps.branch-name.outputs.current_branch }}
